const committee = [
  {
    name: "Aguel Arij",
    role: "Presidente",
    image: "",
    facebook: "",
    phoneNumber: "50532842",
    aerodayAddress: "arij.aguel@aeroday.tn",
    personalEmail: "arij.aguel02@gmail.com",
  },
  {
    name: "BelhajAmor Amine",
    role: "Vice President Technique",
    image: "",
    facebook: "",
    phoneNumber: "94385507",
    aerodayAddress: "amine.belhajamor@aeroday.tn",
    personalEmail: "aminebhj27@gmail.com",
  },
  {
    name: "Emna Ben Ali",
    role: "Vice President Administratif",
    image: "",
    facebook: "",
    phoneNumber: "28289963",
    aerodayAddress: "emna.benali@aeroday.tn",
    personalEmail: "emnabenali0128@gmail.com",
  },
  {
    name: "Sammoud Hamza",
    role: "Resp AirShow",
    image: "",
    facebook: "",
    phoneNumber: "24651753",
    aerodayAddress: "hamza.sammoud@aeroday.tn",
    personalEmail: "hamza.sammoud11@gmail.com",
  },
  {
    name: "Amine Bensaid",
    role: "Resp AeroChallenge",
    image: "",
    facebook: "",
    phoneNumber: "23051505",
    aerodayAddress: "amine.bensaid@aeroday.tn",
    personalEmail: "Aminebensaid66@gmail.com",
  },
  {
    name: "Cherifa Chaouech",
    role: "Resp Videographie par Drone",
    image: "",
    facebook: "",
    phoneNumber: "",
    aerodayAddress: "cherifa.chaouech@aeroday.tn",
    personalEmail: "cherifachaouch7@gmail.com",
  },
  {
    name: "Silini Jihed",
    role: "Resp AeroModelisme",
    image: "",
    facebook: "",
    phoneNumber: "27467595",
    aerodayAddress: "jihed.silini@aeroday.tn",
    personalEmail: "jihed1.silini@gmail.com",
  },
  {
    name: "Kahlaoui Oussema",
    role: "Resp AeroEntrepreneur",
    image: "",
    facebook: "",
    phoneNumber: "52020229",
    aerodayAddress: "oussema.kahlaoui@aeroday.tn",
    personalEmail: "oussemaest89@gmail.com",
  },
  {
    name: "Mohamed Hamzaoui",
    role: "Resp CAO",
    image: "",
    facebook: "",
    phoneNumber: "",
    aerodayAddress: "mohamed.hamzaoui@aeroday.tn",
    personalEmail: "",
  },
  {
    name: "Ksibi Ahmed",
    role: "Resp AeroSpace",
    image: "",
    facebook: "",
    phoneNumber: "92214022",
    aerodayAddress: "ahmed.ksibi@aeroday.tn",
    personalEmail: "ahmed.ksibi9@gmail.com",
  },
  {
    name: "Feten Ben Rejeb",
    role: "Resp Expositions",
    image: "",
    facebook: "",
    phoneNumber: "29180195",
    aerodayAddress: "benrejeb.feten@aeroday.tn",
    personalEmail: "fetenbenrjeb9@gmail.com",
  },
  {
    name: "Laabidi Nour El Houda",
    role: "Resp Ambassadeurs",
    image: "",
    facebook: "",
    phoneNumber: "95864411",
    aerodayAddress: "nourelhoda.laabidi@aeroday.tn",
    personalEmail: "labidinour29@gmail.com",
  },
  {
    name: "Kabadou Nermine",
    role: "Resp Ateliers Novices",
    image: "",
    facebook: "",
    phoneNumber: "52902302",
    aerodayAddress: "nermine.kabadou@aeroday.tn",
    personalEmail: "kabadounermine@gmail.com",
  },
  {
    name: "Nagara Aziza",
    role: "Organisation",
    image: "",
    facebook: "",
    phoneNumber: "52318280",
    aerodayAddress: "aziza.nagara@aeroday.tn",
    personalEmail: "azizanagara0@gmail.com",
  },
  {
    name: "Feriel Elloumi",
    role: "Decoration",
    image: "",
    facebook: "",
    phoneNumber: "53054481",
    aerodayAddress: "feriel.elloumi@aeroday.tn",
    personalEmail: "fefefelelelefefe@gmail.com",
  },
  {
    name: "Ferchichi Imen",
    role: "Secrétaire Générale",
    image: "",
    facebook: "",
    phoneNumber: "58074323",
    aerodayAddress: "imen.ferchichi@aeroday.tn",
    personalEmail: "ferchichiimen.lp@gmail.com",
  },
  {
    name: "Allouch Yessin",
    role: "Trésorier",
    image: "",
    facebook: "",
    phoneNumber: "93203229",
    aerodayAddress: "yessin.allouch@aeroday.tn",
    personalEmail: "yessinallouch65@gmail.com",
  },
  {
    name: "Chabbah Amin",
    role: "Rh",
    image: "",
    facebook: "",
    phoneNumber: "55242726",
    aerodayAddress: "amin.chabbah@aeroday.tn",
    personalEmail: "chabbahamin5@gmail.com",
  },
  {
    name: "Mhamdi Eya",
    role: "Media On",
    image: "",
    facebook: "",
    phoneNumber: "94766307",
    aerodayAddress: "eya.mhamdi@aeroday.tn",
    personalEmail: "eyamhamdi2003@gmail.com",
  },
  {
    name: "Slim Meriem",
    role: "Media Off",
    image: "",
    facebook: "",
    phoneNumber: "23884059",
    aerodayAddress: "meriem.slim@aeroday.tn",
    personalEmail: "slimmeryem75@gmail.com",
  },
  {
    name: "Mahmoudi Maher",
    role: "Multimedia",
    image: "",
    facebook: "",
    phoneNumber: "22214729",
    aerodayAddress: "maher.mahmoudi@aeroday.tn",
    personalEmail: "1maher.mahmoudi1@gmail.com",
  },
  {
    name: "Sahnoun Houssem",
    role: "Web Master",
    image: "",
    facebook: "",
    phoneNumber: "51067304",
    aerodayAddress: "houssem.sahnoun@aeroday.tn",
    personalEmail: "sahnoun.houssem05@gmail.com",
  },
  {
    name: "Laarafa Marwen",
    role: "Photographer",
    image: "",
    facebook: "",
    phoneNumber: "",
    aerodayAddress: "",
    personalEmail: "",
  },
  {
    name: "Cherni Borhen",
    role: "Relations Externes",
    image: "",
    facebook: "",
    phoneNumber: "95474874",
    aerodayAddress: "borhen.cherni@aeroday.tn",
    personalEmail: "borhencher35@gmail.com",
  },
  {
    name: "Besbes Meriem",
    role: "Sponsoring",
    image: "",
    facebook: "",
    phoneNumber: "50349400",
    aerodayAddress: "maryem.besbes@aeroday.tn",
    personalEmail: "besbesbiba@gmail.com",
  },
];

export { committee };
